---
version: "2.0"

services:
  node:
    image: moonbys/cosmos-omnibus:v0.3.26-bitcanna-v1.6.1
    env:
      - MONIKER=R-Drone
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/bitcanna/chain.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    # params:
    #   storage:
    #     data:
    #       mount: /root/.bcna

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
